apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-dev
  namespace:  rd-fluxcd-lesson
spec:
  interval: 1m
  path: ./overlays/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: development
  wait: true
  timeout: 2m
